### ISSUE TITLE
`lt` alias doesn't work

### ISSUE THREAD

**Issue by andreiborisov** [gazorby/fish-exa#1]
It appears `lt` alias doesn't work:

```console
$ lt 2
"2": No such file or directory (os error 2)
```

While `exa --long --all --group --header --tree --level 2` works fine.

**Comment by gazorby** [comment]
Thanks for reporting @andreiborisov!

My last commit 4bb3879361d5acd2b900f336e3eeec49e6f27b3e should fix this, could you confirm?

**Comment by andreiborisov** [comment]
Yep, works like a charm now, thank you!
