### ISSUE TITLE
typo in `i` and `id` ? 

### ISSUE THREAD

**Issue by azinsharaf** [gazorby/fish-exa#10]
i am wondering if this is a typo because `id` returns icons only for directories. 

![image](https://user-images.githubusercontent.com/10101468/211232500-dfe56cbd-09f8-448a-a4bc-b5a4bdb646ab.png)

**Comment by gazorby** [comment]
Good catch! actually, `i` options should be `--icons` and `id` ones `--icons --only-dirs`
