### ISSUE TITLE
exa is unmaintained now, should switch to eza

### ISSUE THREAD

**Issue by haoming-li-ling** [gazorby/fish-exa#12]
As in the title

**Comment by gazorby** [comment]
Thanks for the update, wasn't aware of that. Check for eza added in 99ed6cfb3e45148d5baf3586dfad7279df317263

**Comment by wcasanova** [comment]
README reference to this is missing

**Comment by Alfagun74** [comment]
Additional Sidenote: You must install eza on your system before you install this plugin.
