### ISSUE TITLE
Allow to set options for `l` alias

### ISSUE THREAD

**Issue by andreiborisov** [gazorby/fish-exa#2]
I would like to set options for the `l` alias. It can be useful for showing hidden files by default for example.

**Comment by gazorby** [comment]
Hi @andreiborisov!

I agree with you, this would be consistent with other aliases. Which options would you like to see by default?

**Comment by andreiborisov** [comment]
I’m going to use only `--all`, but it’s highly opinionated, so perhaps no options by default would be a better choice.

**Comment by gazorby** [comment]
Hi @andreiborisov!

Sorry for the late answer, this should be fixed on master by the `EXA_L_OPTIONS` env var.
