### ISSUE TITLE
Improve the default arguments values

### ISSUE THREAD

**Issue by lordlycastle** [gazorby/fish-exa#6]
I have noticed some mistakes in the default set of options, listed below.

We should update them if you agree. [Documentation to exa](https://github.com/ogham/exa#options).

----
# `EXA_LD_OPTIONS`
### Justification
`--list-dirs` **does not** list all directories. I only see the `.` directory.
![image](https://user-images.githubusercontent.com/11729541/140389307-7c36304d-bb05-4123-8efe-b3b904a27e4f.png)

---
# `EXA_STANDARD_OPTIONS`
### Justification
Both `--all` should be part of `la` and `--long` of `ll` respectively. Otherwise they do not behave any differently.

With standard options we want it to behave like a standard `ls`/`exa` with minor or common shared UX improvements arguments.

`EXA_LE_OPTIONS` will need to updated to include `--long` if we update standard options.

## Opinionated Options
It depends on peoples preferences so there is a reason to keep the default options shipped with this plugin to be as little as possible and generally accepted by majority.

Here are some of these options:
 1. `--group-directories-first` Useful as it adds another layer of sorting 

---
# `EXA_LL_OPTIONS`
### Justification
Once we remove this from standard options we will require it here for long output. This seems more appropriate for the option.

---
# `EXA_LA_OPTIONS`
### Justification
Once we remove `--all` we need to add it here to show all files for this command.

It include some options that can be removed as they're not commonly used:
 1. `--inode`: Barely anyone looks at the inode number for a file
 2. `--blocks`: Human readable file size is already shown, so it's arguable how much this adds.
 3. `--links`: Most people might not even what this is supposed to mean.

---
# `EXA_LG_OPTIONS`
### Justification
When you want to list  files in a git repo, you need `--git-ignore`; otherwise you can use any of the other options to list all files.

`--git` only works with `--long` option so if we remove it from standard options we need to add it here too. Though that can also be left for user to decide.

---

**Comment by gazorby** [comment]
Hi @lordlycastle, master has been updated following your suggestions, thank you!

I agree that we need sane, widely accepted defaults. The current ones  are more personal settings rather than defaults.

- `EXA_LD_OPTIONS`

    This one is a bug, `--list-dirs` actually list directories as regular files, we want "only directories"

- `EXA_STANDARD_OPTIONS`

    `--group-directories-first` seems good.
