### ISSUE TITLE
fisher update removes aliases from current shell

### ISSUE THREAD

**Issue by jsumner** [gazorby/fish-exa#7]
After having installed fish-exa using fisher running a "fisher update" will remove the aliases (e.g. ll) for that shell. This only affects the shell that ran the update command - closing and reopening fixes the issue.

Might just need the aliases at the top of the conf/fish-exa.fish file to be pulled into the install function, but there may have been a reason for it being outside :)

**Comment by gazorby** [comment]
Hi @jsumner!

Partially fixed on master ;)
There is still the bug with `ll` as it depends on the `exa_git` function that has been removed during update. Other aliases seems to work though.

**Comment by gazorby** [comment]
Edit: `ll` bug was due to the `functions --erase exa_git`, which has been removed in the latest commit (unneeded as fisher remove the function file)
